#!/usr/bin/env python3
"""Generate system/blockMeshDict for the Rayleigh-Taylor instability box.

Single-block uniform structured hex mesh -- no boundary layer grading is
needed (unlike the airfoil O-grid case) because this is a closed tank with
no external shear flow; resolution only needs to resolve the interface
mixing layer, not a wall boundary layer to the same degree.

Vertex layout follows OpenFOAM's standard box convention (as used in e.g.
the pitzDaily/cavity tutorials): bottom quad (z=0) vertices 0-3 traversed
ccw in the x-y plane, top quad (z=Lz) vertices 4-7 in the same order. This
makes the block's local (i,j,k) directions align exactly with (x,y,z), so
the hex resolution tuple (NX NY NZ) and the cell ordering used by
makeAlphaField.py are unambiguous.

Run:  python3 system/makeBlockMeshDict.py
Output: system/blockMeshDict
"""

# ---------------------------------------------------------------------------
# Parameters (edit here if the mesh needs to be adjusted)
# ---------------------------------------------------------------------------
LX = 0.15    # domain width  (x) [m]
LY = 0.60    # domain height (y) [m] -- vertical, gravity acts along -y
LZ = 0.075   # domain depth  (z) [m] -- halved from the first pass to afford
             # 4x the cell budget at doubled resolution in x/y (the plane
             # that actually captures the RTI plume dynamics) while keeping
             # height/width unchanged, per user request.

NX = 40      # cells in x
NY = 160     # cells in y
NZ = 20      # cells in z
# Total cells = NX*NY*NZ = 128,000 (4x the original 32,000)
# Uniform cubic cells, h = 3.75 mm (half the original 7.5 mm in every
# direction) -- resolution doubled, not just cell count increased.


def fmt(p):
    return f"({p[0]:.6f} {p[1]:.6f} {p[2]:.6f})"


def main():
    # Standard box vertex order: bottom (z=0) 0-3 ccw in x-y, top (z=Lz) 4-7
    # in the same relative order (i=x, j=y, k=z local block directions).
    corners = [
        (0.0, 0.0, 0.0),   # 0
        (LX, 0.0, 0.0),    # 1
        (LX, LY, 0.0),     # 2
        (0.0, LY, 0.0),    # 3
        (0.0, 0.0, LZ),    # 4
        (LX, 0.0, LZ),     # 5
        (LX, LY, LZ),      # 6
        (0.0, LY, LZ),     # 7
    ]

    vertices_lines = [f"    {fmt(p)} // {i}" for i, p in enumerate(corners)]

    text = f"""/*--------------------------------*- C++ -*----------------------------*\\
| =========                 |                                                |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox         |
|  \\\\    /   O peration     | Version:  v2412                               |
|   \\\\  /    A nd           | Web:      www.openfoam.com                    |
|    \\\\/     M anipulation  |                                                |
\\*-----------------------------------------------------------------------*/
// AUTO-GENERATED by system/makeBlockMeshDict.py -- do not hand-edit.
// Regenerate with: python3 system/makeBlockMeshDict.py
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

scale   1;

vertices
(
{chr(10).join(vertices_lines)}
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({NX} {NY} {NZ}) simpleGrading (1 1 1)
);

edges
(
);

boundary
(
    bottom
    {{
        type wall;
        faces
        (
            (0 1 5 4)
        );
    }}
    top
    {{
        type wall;
        faces
        (
            (3 7 6 2)
        );
    }}
    left
    {{
        type wall;
        faces
        (
            (0 4 7 3)
        );
    }}
    right
    {{
        type wall;
        faces
        (
            (1 2 6 5)
        );
    }}
    front
    {{
        type wall;
        faces
        (
            (0 3 2 1)
        );
    }}
    back
    {{
        type wall;
        faces
        (
            (4 5 6 7)
        );
    }}
);

// ************************************************************************* //
"""
    with open("system/blockMeshDict", "w", newline="\n") as f:
        f.write(text)
    print("Wrote system/blockMeshDict")
    print(f"  Domain: {LX} x {LY} x {LZ} m, cells: {NX}x{NY}x{NZ} = {NX*NY*NZ}")
    print(f"  Cell size: dx={LX/NX*1000:.2f}mm dy={LY/NY*1000:.2f}mm dz={LZ/NZ*1000:.2f}mm")


if __name__ == "__main__":
    main()
