#!/usr/bin/env python3
"""Generate 0/alpha.heavy with a SINGLE-MODE interface perturbation --
produces one clean, symmetric "mushroom" plume in the centre of the domain,
in contrast to the multi-mode random perturbation used in the sibling
RayleighTaylorDES case (see that case's CLAUDE.md for the multi-mode
version, and the top-level comparison note for why each was chosen).

The mesh is a plain uniform structured box (see makeBlockMeshDict.py), so
cell centers can be computed analytically without needing to read blockMesh
output. alpha.heavy = 1 above the (perturbed) interface, 0 below.

Interface height (measured from the bottom, y-direction):
    y_interface(x, z) = Y0 + A * sin(pi*x/Lx) * sin(pi*z/Lz)

Using pi (half a period) rather than 2*pi means the perturbation is exactly
zero at all four side walls (x=0, x=Lx, z=0, z=Lz) and reaches a single
smooth maximum at the domain centre -- one dome, not a checkerboard of
several. No randomness is involved; this is fully deterministic.

Run:  python3 system/makeAlphaField.py
Output: 0/alpha.heavy
"""
import math

# ---------------------------------------------------------------------------
# Must match system/makeBlockMeshDict.py
# ---------------------------------------------------------------------------
LX = 0.15
LY = 0.60
LZ = 0.075
NX = 40
NY = 160
NZ = 20

Y0 = LY / 2.0                 # mean interface height (mid-domain)
AMPLITUDE = 0.02 * LY         # single-mode amplitude (~2% of domain height,
                               # same magnitude budget as the multi-mode case
                               # for a fair comparison)

FIELD_NAME = "alpha.heavy"


def interface_height(x, z):
    return Y0 + AMPLITUDE * math.sin(math.pi * x / LX) * math.sin(math.pi * z / LZ)


def cell_centers_1d(n, length):
    dx = length / n
    return [(i + 0.5) * dx for i in range(n)]


def main():
    xs = cell_centers_1d(NX, LX)
    ys = cell_centers_1d(NY, LY)
    zs = cell_centers_1d(NZ, LZ)

    # blockMesh cell ordering for a single hex block built with the standard
    # box vertex convention: x fastest, then y, then z (see
    # makeBlockMeshDict.py's vertex-layout comment).
    values = []
    n_heavy = 0
    for k in range(NZ):
        z = zs[k]
        for j in range(NY):
            y = ys[j]
            for i in range(NX):
                x = xs[i]
                yi = interface_height(x, z)
                v = 1 if y > yi else 0
                n_heavy += v
                values.append(v)

    n_total = NX * NY * NZ
    print(f"Single-mode perturbation: amplitude={AMPLITUDE*1000:.2f}mm, "
          f"centre bulge at (x={LX/2*1000:.1f}mm, z={LZ/2*1000:.1f}mm)")
    print(f"Heavy-fluid cells: {n_heavy}/{n_total} ({100*n_heavy/n_total:.1f}%) "
          f"-- expect close to 50% since interface is at mid-height")

    header = f"""/*--------------------------------*- C++ -*----------------------------*\\
| =========                 |                                                |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox         |
|  \\\\    /   O peration     | Version:  v2412                               |
|   \\\\  /    A nd           | Web:      www.openfoam.com                    |
|    \\\\/     M anipulation  |                                                |
\\*-----------------------------------------------------------------------*/
// AUTO-GENERATED by system/makeAlphaField.py -- do not hand-edit the
// internalField below. Regenerate with: python3 system/makeAlphaField.py
FoamFile
{{
    version     2.0;
    format      ascii;
    class       volScalarField;
    object      {FIELD_NAME};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

dimensions      [0 0 0 0 0 0 0];

internalField   nonuniform List<scalar>
{n_total}
(
"""
    body = "\n".join(str(v) for v in values)
    footer = """
)
;

boundaryField
{
    bottom  { type zeroGradient; }
    top     { type zeroGradient; }
    left    { type zeroGradient; }
    right   { type zeroGradient; }
    front   { type zeroGradient; }
    back    { type zeroGradient; }
}

// ************************************************************************* //
"""
    with open("0/alpha.heavy", "w", newline="\n") as f:
        f.write(header + body + footer)
    print("Wrote 0/alpha.heavy")


if __name__ == "__main__":
    main()
